# Generated by Django 3.1.5 on 2021-03-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20210325_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
